/**
 * Maps short language codes (used for CLI args and output directory names)
 * to the full English language names required by translation APIs.
 */
export const LANGUAGE_CODES: Record<string, string> = {
  en: "English",
  zh: "Chinese",
  zh_tw: "Traditional Chinese",
  ru: "Russian",
  ja: "Japanese",
  ko: "Korean",
  es: "Spanish",
  fr: "French",
  pt: "Portuguese",
  de: "German",
  it: "Italian",
  th: "Thai",
  vi: "Vietnamese",
  id: "Indonesian",
  ms: "Malay",
  ar: "Arabic",
  hi: "Hindi",
  he: "Hebrew",
  my: "Burmese",
  ta: "Tamil",
  ur: "Urdu",
  bn: "Bengali",
  pl: "Polish",
  nl: "Dutch",
  ro: "Romanian",
  tr: "Turkish",
  km: "Khmer",
  lo: "Lao",
  yue: "Cantonese",
  cs: "Czech",
  el: "Greek",
  sv: "Swedish",
  hu: "Hungarian",
  da: "Danish",
  fi: "Finnish",
  uk: "Ukrainian",
  bg: "Bulgarian",
  sr: "Serbian",
  te: "Telugu",
  af: "Afrikaans",
  hy: "Armenian",
  as: "Assamese",
  ast: "Asturian",
  eu: "Basque",
  be: "Belarusian",
  bs: "Bosnian",
  ca: "Catalan",
  ceb: "Cebuano",
  hr: "Croatian",
  arz: "Egyptian Arabic",
  et: "Estonian",
  gl: "Galician",
  ka: "Georgian",
  gu: "Gujarati",
  is: "Icelandic",
  jv: "Javanese",
  kn: "Kannada",
  kk: "Kazakh",
  lv: "Latvian",
  lt: "Lithuanian",
  lb: "Luxembourgish",
  mk: "Macedonian",
  mai: "Maithili",
  mt: "Maltese",
  mr: "Marathi",
  acm: "Mesopotamian Arabic",
  ary: "Moroccan Arabic",
  ars: "Najdi Arabic",
  ne: "Nepali",
  az: "North Azerbaijani",
  apc: "North Levantine Arabic",
  uz: "Northern Uzbek",
  nb: "Norwegian Bokmål",
  nn: "Norwegian Nynorsk",
  oc: "Occitan",
  or: "Odia",
  pag: "Pangasinan",
  scn: "Sicilian",
  sd: "Sindhi",
  si: "Sinhala",
  sk: "Slovak",
  sl: "Slovenian",
  ajp: "South Levantine Arabic",
  sw: "Swahili",
  tl: "Tagalog",
  acq: "Ta'izzi-Adeni Arabic",
  sq: "Tosk Albanian",
  aeb: "Tunisian Arabic",
  vec: "Venetian",
  war: "Waray",
  cy: "Welsh",
  fa: "Western Persian",
};

/**
 * Resolves a language code (e.g. "ja") to its full English name (e.g. "Japanese").
 * If the code is not found in the map, returns the input unchanged — this allows
 * passing full names directly (e.g. "Japanese") as a fallback.
 */
export function resolveLanguageName(codeOrName: string): string {
  return LANGUAGE_CODES[codeOrName] ?? codeOrName;
}
